
Extract from Pride And Prejudice


It is a truth universally acknowledged, that a single man in
possession of a good fortune, must be in want of a wife.







page 1


Extract from Pride And Prejudice


However little known the feelings of views of such a man may
be  on  his first entering a neighbourhood, this truth is so
well  fixed in the minds of the surrounding families that he
is  considered as the rightful property of some one or other
of their daughters.




page 2

