          [4mCover[0m [4mtext[0m [4mfrom[0m [4mSoftware[0m [4mTools[0m [4min[0m [4mPascal[0m

Good  Programming  is  not learned from generalities, but by
seeing how significant programs can be made clean,  easy  to
read,   easy   to  maintain  and  modify,  human-engineered,
efficient, and reliable, by the application of common  sense
and  good programming practices. Careful study and imitation
of good programs leads to better writing.


























































